language: php
php:
- 5.5
- 5.6
- 7.0
sudo: false
script:
  - find Configuration Classes -name '*.php' | xargs -l1 php -l
before_deploy:
  - ./build-release.sh ${TRAVIS_TAG/v/}
deploy:
  provider: releases
  api_key:
    secure: HqH5f3DZc/DlYmhUNMWEnbaztInIToFwjc++d7Xniq69WeT3PUDICh4Bd5X7I+ZcFS5s1hRpveBcJNwrqfP/W+JJrEw6brcE5GVXlNFTULaHGkF0G/rmeeIPCxKAjMsWbX5gpNI8jWlB6ZmWmzs+mOLtGYTts3oO268SJHc9ZwMKM6kye4VvEH1JRyQ/jrSMOi70w3Bu7VnICJUwvqLYPVvynxhcZOqJBikrGTKKZACVqTOPdFHi2HGeuN3tf5k25tKHAC2ShkPOqztbgJfFCvN+Nka+pkGKTR7QDsoCQftQZ4mBqpP4JsJDcSMccZLRkxlNwEYwVLPgRRkfhxC6+i3y1sn6236JBB2RVN6BBk6JGGY7lOrPeuEkbkWwkVMAqNxvYSX+RS+sUOahQGUOoaa01lqnRdbysIIb768I52NUuPrg1RDRmYpDFCBMkCUfRZEABKx5J3FHqTPBrSpGrkmFATkwApizJ3WCcFjN3YX8wSjJm2h3v3b0E54JYFK5xS7JglFdCyM15jdKZ/9HkyMvccN5xDnSVK1DigV+8kQ/dxkWgsGN+kT0OkuGnZyccOCqno7ce8SNAeE0+jZedlYgub8wtWv11c+YStNP1oUxn7WPOkBIawscbW3qVjhocN03aJisJ6sn8P6YRUf4YIVtTiWgGklwGF1OFCQGS6M=
  file_glob: true
  file: varnishcache_*.zip
  on:
    repo: filoucrackeur/typo3-varnishcache
    tags: true
    php: 5.6
